# Generated by Django 4.0.2 on 2022-02-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitdata',
            name='Summer_Rating',
            field=models.CharField(default='Beddington', max_length=100),
        ),
        migrations.AddField(
            model_name='circuitdata',
            name='Winter_Rating',
            field=models.CharField(default='Beddington', max_length=100),
        ),
        migrations.AddField(
            model_name='circuitdata',
            name='cir_leng',
            field=models.CharField(default='Beddington', max_length=100),
        ),
        migrations.AddField(
            model_name='circuitdata',
            name='dest_node',
            field=models.CharField(default='Beddington', max_length=100),
        ),
        migrations.AddField(
            model_name='circuitdata',
            name='dest_substation',
            field=models.CharField(default='Beddington', max_length=100),
        ),
        migrations.AddField(
            model_name='circuitdata',
            name='line_name',
            field=models.CharField(default='Beddington', max_length=100),
        ),
        migrations.AddField(
            model_name='circuitdata',
            name='oper_vol',
            field=models.CharField(default='Beddington', max_length=100),
        ),
        migrations.AddField(
            model_name='circuitdata',
            name='pos_B',
            field=models.CharField(default='Beddington', max_length=100),
        ),
        migrations.AddField(
            model_name='circuitdata',
            name='pos_R',
            field=models.CharField(default='Beddington', max_length=100),
        ),
        migrations.AddField(
            model_name='circuitdata',
            name='pos_X',
            field=models.CharField(default='Beddington', max_length=100),
        ),
        migrations.AlterField(
            model_name='circuitdata',
            name='GSP',
            field=models.CharField(default='Beddington', max_length=100),
        ),
        migrations.AlterField(
            model_name='circuitdata',
            name='Node',
            field=models.CharField(default='Beddington', max_length=100),
        ),
        migrations.AlterField(
            model_name='circuitdata',
            name='Substation',
            field=models.CharField(default='Beddington', max_length=100),
        ),
    ]
