# Generated by Django 4.0 on 2022-02-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0002_circuitdata_summer_rating_circuitdata_winter_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='earthFaultData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSP', models.CharField(max_length=50)),
                ('Substn', models.CharField(max_length=50)),
                ('NodeName', models.CharField(max_length=50)),
                ('VoltLvl_kV', models.CharField(max_length=50)),
                ('SysImp_R', models.CharField(max_length=50)),
                ('SysImp_X', models.CharField(max_length=50)),
                ('ESFC_PeakMake_kA', models.CharField(max_length=50)),
                ('ESFC_RMSBreak_kA', models.CharField(max_length=50)),
                ('FR_PeakMake_kA', models.CharField(max_length=50)),
                ('FR_Break_kA', models.CharField(max_length=50)),
                ('Network_Area', models.CharField(default='EPN', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FaultData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSP', models.CharField(max_length=50)),
                ('Substn', models.CharField(max_length=50)),
                ('NodeName', models.CharField(max_length=50)),
                ('VoltLvl_kV', models.CharField(max_length=50)),
                ('ResPro_Mit_Rev', models.CharField(max_length=150)),
                ('ActYr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSP', models.CharField(max_length=50)),
                ('Substn', models.CharField(max_length=50)),
                ('ConVolt_kV', models.CharField(max_length=50)),
                ('InsCap_MW', models.CharField(max_length=50)),
                ('FuelType', models.CharField(max_length=50)),
                ('ConAcc', models.CharField(max_length=50)),
                ('Network_Area', models.CharField(default='EPN', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InterestConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSP', models.CharField(max_length=50)),
                ('Substn', models.CharField(max_length=50)),
                ('PCVolt_kV', models.CharField(max_length=50)),
                ('ConStat', models.CharField(max_length=50)),
                ('Dem_TN', models.CharField(max_length=50)),
                ('Dem_TC', models.CharField(max_length=50)),
                ('Gen_TN', models.CharField(max_length=50)),
                ('Gen_TC', models.CharField(max_length=50)),
                ('Network_Area', models.CharField(default='EPN', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSP', models.CharField(max_length=50)),
                ('Substn', models.CharField(max_length=50)),
                ('Season', models.CharField(max_length=50)),
                ('MaxDem_19_20_MW', models.CharField(max_length=50)),
                ('MaxDem_19_20_PF', models.CharField(max_length=50)),
                ('MaxDem_20_21', models.CharField(max_length=50)),
                ('MaxDem_21_22', models.CharField(max_length=50)),
                ('MaxDem_22_23', models.CharField(max_length=50)),
                ('MaxDem_23_24', models.CharField(max_length=50)),
                ('MaxDem_24_25', models.CharField(max_length=50)),
                ('FirmCap_MW', models.CharField(max_length=50)),
                ('MinLoadSF', models.CharField(max_length=50)),
                ('Network_Area', models.CharField(default='EPN', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OppRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSP', models.CharField(max_length=50)),
                ('Substn', models.CharField(max_length=50)),
                ('FL_OpRes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='phFaultData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSP', models.CharField(max_length=50)),
                ('Substn', models.CharField(max_length=50)),
                ('NodeName', models.CharField(max_length=50)),
                ('VoltLvl_kV', models.CharField(max_length=50)),
                ('SysImp_R', models.CharField(max_length=50)),
                ('SysImp_X', models.CharField(max_length=50)),
                ('ESFC_PeakMake_kA', models.CharField(max_length=50)),
                ('ESFC_RMSBreak_kA', models.CharField(max_length=50)),
                ('FR_PeakMake_kA', models.CharField(max_length=50)),
                ('FR_Break_kA', models.CharField(max_length=50)),
                ('Network_Area', models.CharField(default='EPN', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransformerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSP', models.CharField(max_length=50)),
                ('HV_Node', models.CharField(max_length=50)),
                ('HV_Substn', models.CharField(max_length=50)),
                ('VoltHV_kV', models.CharField(max_length=50)),
                ('LV_Node', models.CharField(max_length=50)),
                ('LV_Substn', models.CharField(max_length=50)),
                ('VoltLV_kV', models.CharField(max_length=50)),
                ('VecGrp', models.CharField(max_length=50)),
                ('PSeqImp_R', models.CharField(max_length=50)),
                ('PSeqImp_X', models.CharField(max_length=50)),
                ('ZSeqImp_X', models.CharField(max_length=50)),
                ('TapMin', models.CharField(max_length=50)),
                ('TapMax', models.CharField(max_length=50)),
                ('TRatingMVA_Sum', models.CharField(max_length=50)),
                ('TRatingMVA_Win', models.CharField(max_length=50)),
                ('RevPowCap', models.CharField(max_length=50)),
                ('Earth_HV', models.CharField(max_length=50)),
                ('Earth_LV', models.CharField(max_length=50)),
                ('Network_Area', models.CharField(default='EPN', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='circuitdata',
            name='Network_Area',
            field=models.CharField(default='EPN', max_length=100),
        ),
    ]
